version: "2"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile-development
    ports:
      - 80:80
    volumes:
      - ./app:/var/www/html
    env_file:
        - ./app/env/.env

  mysql:
    image: mariadb:latest
    ports:
        - 3306:3306
    volumes:
        - db_data:/var/lib/mysql
    env_file:
        - ./app/env/.env

  redis:
    image: redis:latest
volumes:
  db_data: