version: "3"
services:
  wordpress:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    env_file:
        - ./app/env/.env

  mysql:
    image: mariadb:latest
    ports:
        - 3306:3306
    volumes:
        - db_data:/var/lib/mysql
    env_file:
        - ./app/env/.env
        
  redis:
    image: redis:3.2.11