---
- hosts: all
  user: evermade
  sudo: true
  vars:
    username: evermade
  roles:
   - { role: precheck, tags: [precheck] }
   - { role: nginx, tags: [nginx] }
   - { role: php, tags: [php] }
   - { role: mariadb, tags: [mariadb] }
   - { role: wp-cli, tags: [wpcli] }
