<?php

// https://www.advancedcustomfields.com/resources/register-fields-via-php/

return array(
          'key' => 'group_'.$blockName,
          'name' => $blockName,
          'label' => str_replace('-', ' ', ucfirst($blockName)),
					'display' => 'row',
					'sub_fields' => array(
						array(
              'key' => 'field_'.$blockName.'_content',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
              'key' => 'field_'.$blockName.'_columns',
							'label' => 'Columns',
							'name' => 'columns',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 1,
							'max' => 4,
							'layout' => 'block',
							'button_label' => 'Add Column',
							'sub_fields' => array(
								array(
                  'key' => 'field_'.$blockName.'_column',
									'label' => 'Content',
									'name' => 'column',
									'type' => 'wysiwyg',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'tabs' => 'all',
									'toolbar' => 'full',
									'media_upload' => 1,
									'delay' => 0,
								),
							),
						),
						array(
              'key' => 'field_'.$blockName.'_settings',
							'label' => 'Settings',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
              'key' => 'field_'.$blockName.'_horizontal_alignment',
							'label' => 'Content Horizontal Alignment',
							'name' => 'horizontal_alignment',
							'type' => 'select',
							'instructions' => 'This should be used when only 1 column is used, else will not take effect. It will center align the content container, but not the content itself, as that styling can be done in the wysiwyg editor upon context.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33.333333',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'h-left' => 'Left',
								'h-center' => 'Center',
							),
							'default_value' => array(
								0 => 'h-left',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				);
