<?php

// https://www.advancedcustomfields.com/resources/register-fields-via-php/

return array(
          'key' => 'group_'.$blockName,
          'name' => $blockName,
          'label' => str_replace('-', ' ', ucfirst($blockName)),
					'display' => 'row',
					'sub_fields' => array(
						array(
							'key' => 'field_'.$blockName.'_tab1',
							'label' => 'Content',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_'.$blockName.'_layout',
							'label' => 'Layout',
							'name' => 'layout',
							'type' => 'radio',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'left' => '<span class="dashicons dashicons-editor-alignleft"></span> <span class="dashicons dashicons-format-image"></span>',
								'right' => '<span class="dashicons dashicons-format-image"></span> <span class="dashicons dashicons-editor-alignleft"></span>',
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'save_other_choice' => 0,
							'default_value' => 'left',
							'layout' => 'vertical',
							'return_format' => 'value',
						),
						array(
							'key' => 'field_'.$blockName.'_image',
							'label' => 'Image',
							'name' => 'image',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_'.$blockName.'_text',
							'label' => 'Text',
							'name' => 'text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 1,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
						array(
							'key' => 'field_'.$blockName.'_tab2',
							'label' => 'Foreground Image',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_'.$blockName.'_image_foreground',
							'label' => 'Foreground Image',
							'name' => 'image_foreground',
							'type' => 'image',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'return_format' => 'array',
							'preview_size' => 'thumbnail',
							'library' => 'all',
							'min_width' => '',
							'min_height' => '',
							'min_size' => '',
							'max_width' => '',
							'max_height' => '',
							'max_size' => '',
							'mime_types' => '',
						),
						array(
							'key' => 'field_'.$blockName.'_image_foreground_vertical_alignment',
							'label' => 'Foreground Vertical Alignment',
							'name' => 'image_foreground_vertical_alignment',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'top' => 'Top',
								'middle' => 'Middle',
								'bottom' => 'Bottom',
							),
							'default_value' => array(
								0 => 'middle',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
						array(
							'key' => 'field_'.$blockName.'_image_foreground_maximum_width',
							'label' => 'Foreground Maximum Width',
							'name' => 'image_foreground_maximum_width',
							'type' => 'number',
							'instructions' => 'Maximum width in pixels.',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => 0,
							'max' => 2000,
							'step' => '',
						),
						array(
							'key' => 'field_'.$blockName.'_tab3',
							'label' => 'Settings',
							'name' => '',
							'type' => 'tab',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'placement' => 'top',
							'endpoint' => 0,
						),
						array(
							'key' => 'field_'.$blockName.'_layout_width',
							'label' => 'Full width',
							'name' => 'layout_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'full-width' => 'Yes, the image goes to the edge of the website',
								'container-width' => 'No, the image is only 50% of the content width',
							),
							'default_value' => array(
								0 => 'full-width',
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 0,
							'ajax' => 0,
							'return_format' => 'value',
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				);
